services:
    api:
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        container_name: news-aggregator-api
        command: bash -c "/usr/local/bin/wait-for-it-bash db:3306 -- /usr/local/bin/start"
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: api
            SERVICE_TAGS: dev
            HAS_APP_KEY: ${APP_KEY}
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/api/php.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
        - db
        networks:
        - sail

    webserver:
        image: nginx:mainline-alpine
        container_name: news-aggregator-webserver
        restart: unless-stopped
        tty: true
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
            - phpmyadmin_data:/var/www/phpmyadmin/
        networks:
            - sail

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:fpm-alpine
        container_name: news-aggregator-phpmyadmin
        platform: linux/amd64 #required apple/amd chip
        restart: unless-stopped
        environment:
            PMA_ABSOLUTE_URI: ${APP_URL}/phpmyadmin/
        volumes:
            - phpmyadmin_data:/var/www/html/
        networks:
            - sail

    db:
        image: 'mysql/mysql-server:8.0'
        container_name: newsdb
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        container_name: news-aggregator-redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    phpmyadmin_data:
        driver: local
